/**
 * Stable storage API facade. Implementations are split by responsibility so
 * extension entrypoints and tests keep one compatibility boundary.
 */
export {
  GUIDE_DESCRIPTION_MAX_LENGTH,
  GUIDE_TITLE_MAX_LENGTH,
  GuideStructureIntegrityError,
  STEP_STORAGE_LIMITS,
  StepStorageValidationError,
  UNTITLED_GUIDE_BASE,
  buildStepEntries,
  entryId,
  flattenEntries,
  getEffectiveBounds,
  getEntryImageOwner,
  getEntryPrivacyState,
  getOrderedAnnotations,
  isValidBounds,
  stepRole,
  type StepRole,
  type Bounds,
  type EntryPrivacyState,
  type Guide,
  type GuideSection,
  type GuideSummary,
  type OrderedAnnotation,
  type Redaction,
  type ScreenshotStep,
  type Step,
  type StepEntry,
} from './models';
export { closeDatabase, isPristineGuide } from './database';
export { PERSISTED_STEP_LIMITS } from './persistence-limits';
export {
  createGuide,
  createGuideFromSteps,
  deleteGuidePermanently,
  discardPristineGuide,
  duplicateGuide,
  ensureGuide,
  getGuide,
  getGuideSummaries,
  resetGuide,
  updateGuide,
  type CreateGuideFromStepsOptions,
} from './guide-repository';
export {
  GuideContentConflictError,
  addGuideSectionAtomically,
  deleteGuideAnnotationAtomically,
  deleteGuideEntriesAtomically,
  deleteGuideSectionAtomically,
  getGuideStructureSnapshot,
  moveGuideEntriesAtomically,
  renameGuideSectionAtomically,
  reorderGuideAnnotationsAtomically,
  reorderGuideEntriesAtomically,
  restoreGuideAnnotationAtomically,
  restoreGuideEntriesAtomically,
  setGuideEntriesNumberedAtomically,
  type DeleteGuideAnnotationResult,
  type GuideStructureMutationResult,
  type GuideStructureSnapshot,
  type ReorderGuideAnnotationsResult,
  type ReorderGuideEntriesResult,
} from './guide-structure';
export {
  StepDescriptionConflictError,
  StepNotFoundError,
  StepRecaptureError,
  StepUpdateConflictError,
  addStep,
  addSteps,
  deleteStep,
  deleteStepsAndReorder,
  deleteStepsForRun,
  getStep,
  getSteps,
  reorderSteps,
  replaceStepCaptureAtomically,
  restoreStepsAndReorder,
  saveStepDescription,
  updateStep,
  updateStepsAtomically,
  type CaptureReplacement,
  type StepRecaptureTarget,
  type StepUpdate,
} from './step-repository';
